CREATE SCHEMA test;
GO

CREATE TABLE test.Year (
Id INT NOT NULL,
Name INT NOT NULL
);

ALTER TABLE test.Year
ADD CONSTRAINT PK_Year PRIMARY KEY (Id); 

ALTER TABLE test.Year
DROP CONSTRAINT PK_Year;

ALTER TABLE test.Year
DROP COLUMN Id;

ALTER TABLE test.Year
ADD Id INT IDENTITY (1,1) CONSTRAINT PK_Year PRIMARY KEY;